Update Jenkinsfile

diff --git a/Jenkins/nodeapp/Jenkinsfile b/Jenkins/nodeapp/Jenkinsfile
--- a/Jenkins/nodeapp/Jenkinsfile
+++ b/Jenkins/nodeapp/Jenkinsfile
@@ -1,42 +1,46 @@
-node{
-	try{
-	  stage('Checkout'){
-		git url: 'https://github.com/thejk726/DevOps.git' ,branch: 'main'
-		}
-	
-	stage('Provisioning'){
-		sh 'npm install'
-		}
-	
-	stage('Build'){
-		sh 'npm run build || echo "[!] No build step defined..."'
-		}
-	
-	stage('Test'){
-		sh 'npm test'
-	}
+node {
+    try {
+        stage('Checkout') {
+            git url: 'https://github.com/thejk726/DevOps.git', branch: 'main'
+        }
+        
+        stage('Provisioning') {
+            sh 'npm install'
+        }
+        
+        stage('Build') {
+            sh 'npm run build || echo "[!] No build step defined..."'
+        }
+        
+        stage('Test') {
+            sh 'npm test'
+        }
 
-	stage('Deploy to staging'){
-		sh './deploy.sh'
-		}
+        stage('Deploy to staging') {
+            sh './deploy.sh'
+        }
 
-	//Notify success
-	mail to: 'thejkiran726@gmail.com',
-		subject: "Pipeline success! ${env.JOB_NAME} #${env.BUILD_NUMBER}",
-		body: "Good news! The build ${env.JOB_NAME} #${env.BUILD_NUMBER} successful!"
-	echo 'Pipeline successful!'
-	} catch(Exception e){
-	//Notify failure
-	mail to: 'thejkiran726@gmail.com'
-		subject: "Pipeline failed! ${env.JOB_NAME} #${env.BUILD_NUMBER}",
-		body: "Unfortunately the build ${env.JOB_NAME} #${env.BUILD_NUMBER} has failed!"
-
-	echo 'Pipeline failed!'
-	currentBuild.result='FAILURE'
-	throw e
-	} finally{
-	//Archive test results and artifacts
-	archiveArtifacts artifacts: '**/nodeapp/**' allowEmptyArchive: true
-	junit 'nodeapp/test-results.xml'
-}
+        // Notify success
+        mail(
+            to: 'thejkiran726@gmail.com',
+            subject: "Pipeline success! ${env.JOB_NAME} #${env.BUILD_NUMBER}",
+            body: "Good news! The build ${env.JOB_NAME} #${env.BUILD_NUMBER} was successful!"
+        )
+        echo 'Pipeline successful!'
+    } catch(Exception e) {
+        // Notify failure
+        mail(
+            to: 'thejkiran726@gmail.com',
+            subject: "Pipeline failed! ${env.JOB_NAME} #${env.BUILD_NUMBER}",
+            body: "Unfortunately, the build ${env.JOB_NAME} #${env.BUILD_NUMBER} has failed!"
+        )
+        
+        echo 'Pipeline failed!'
+        currentBuild.result = 'FAILURE'
+        throw e
+    } finally {
+        // Archive test results and artifacts
+        archiveArtifacts artifacts: '**/nodeapp/**', allowEmptyArchive: true
+        junit 'nodeapp/test-results.xml'
+    }
 }
